Seguimiento/Models/Carrito.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Seguimiento.Models
{
    public class Carrito
    {
        [Key]
        public int id { get; set; }

        public int idProducto { get; set; }

        [StringLength(20)]
        public string idNombre { get; set; }

        public int idTalle { get; set; }

        public double idPrecio { get; set; }

        public double totalCompra { get; set; }
        
    }
}

Seguimiento/Controllers/CarritosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Seguimiento.Models;

namespace Seguimiento.Controllers
{
    public class CarritosController : Controller
    {
        private readonly SeguimientoContext _context;

        public CarritosController(SeguimientoContext context)
        {
            _context = context;
        }

        // GET: Carritos
        public async Task<IActionResult> Index()
        {
            var empleados = await _context.Empleados.ToListAsync();
            var clientes = await _context.Clientes.ToListAsync();
            var listado = await _context.Carritos.ToListAsync();
            if(listado.Count() != 0)
            {
                ViewBag.total = listado[listado.Count() - 1].totalCompra;
            }
            ViewBag.emp = empleados;
            ViewBag.cli = clientes;
            return View(await _context.Carritos.ToListAsync());
        }

        // GET: Carritos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carrito = await _context.Carritos
                .FirstOrDefaultAsync(m => m.id == id);
            if (carrito == null)
            {
                return NotFound();
            }

            return View(carrito);
        }

        //ACTION CUSTOM, EJECUTA Y LLAMA A INDEX DE HOME
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Crear([Bind("id, idProducto, idNombre, idPrecio, idTalle, totalCompra")] Carrito carrito)
        {
            if (ModelState.IsValid)
            {
                _context.Add(carrito);
                int id = carrito.idProducto;

                var prod = await _context.Productos.FindAsync(id);
                prod.cantidad = prod.cantidad - 1;
                _context.Update(prod);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index", "Home", null);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteAll()
        {
            var lista = await _context.Carritos.ToListAsync();


            foreach (var i in lista)
            {
                var carrito = await _context.Carritos.FindAsync(i.id);
                int id = carrito.idProducto;
                var prod = await _context.Productos.FindAsync(id);

                if (prod != null)

                {
                    prod.cantidad = prod.cantidad + 1;
                    _context.Update(prod);
                }

                _context.Carritos.Remove(i);
                await _context.SaveChangesAsync();
            }

            return View("Index");
        }


        // GET: Carritos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carrito = await _context.Carritos.FindAsync(id);
            if (carrito == null)
            {
                return NotFound();
            }
            return View(carrito);
        }

        // POST: Carritos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id, idProducto, idNombre, idPrecio, idTalle")] Carrito carrito)
        {
            if (id != carrito.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(carrito);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarritoExists(carrito.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(carrito);
        }

        // GET: Carritos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carrito = await _context.Carritos
                .FirstOrDefaultAsync(m => m.id == id);

            if (carrito == null)
            {
                return NotFound();
            }

            return View(carrito);
        }

        // POST: Carritos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var carrito = await _context.Carritos.FindAsync(id);

            int idNuevo = carrito.idProducto;

            var prod = await _context.Productos.FindAsync(idNuevo);
            
            if (prod!= null)
            
            {
                prod.cantidad = prod.cantidad + 1;
                _context.Update(prod);
            }

            _context.Carritos.Remove(carrito);

            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home", null);
        }

        private bool CarritoExists(int id)
        {
            return _context.Carritos.Any(e => e.id == id);
        }
    }
}

Seguimiento/Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Seguimiento.Models;

namespace Seguimiento.Controllers
{
    public class PedidosController : Controller
    {
        private readonly SeguimientoContext _context;

        public PedidosController(SeguimientoContext context)
        {
            _context = context;
        }

        // GET: Pedidos
        public async Task<IActionResult> Index()
        {
            var empleados = await _context.Empleados.ToListAsync();
            var clientes = await _context.Clientes.ToListAsync();
            var productos = await _context.Productos.ToListAsync();
            var compra = await _context.Compras.ToListAsync();
            var direccion = await _context.Direcciones.ToListAsync();
            var carritos = await _context.Carritos.ToListAsync();

            ViewBag.emp = empleados;
            ViewBag.cli = clientes;
            ViewBag.prod = productos;
            ViewBag.comp = compra;
            ViewBag.dir = direccion;
            ViewBag.carr = carritos;
            ViewBag.idLista = "idLista";
            ViewBag.idCliente = "idCliente";
            return View(await _context.Pedidos.ToListAsync());
        }

        // GET: Pedidos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos
                .FirstOrDefaultAsync(m => m.id == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // POST: Pedidos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Crear([Bind("totalCompra, empleadoId, clienteId, nroTraking,comentarios,fechaEnvio,fechaInicio, estado")] Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pedido);
                await _context.SaveChangesAsync();
            }

            var lista = await _context.Carritos.ToListAsync();


            foreach (var i in lista)
            {
                Compra c = new Compra(pedido.id, i.idProducto);
                _context.Compras.Add(c);
                await _context.SaveChangesAsync();
            }


            foreach (var i in lista)
            {
                _context.Carritos.Remove(i);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index", "Home", null);
        }



        // GET: Pedidos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var pedido = await _context.Pedidos.FindAsync(id);
            if (pedido == null)
            {
                return NotFound();
            }
            return View(pedido);
        }

        // POST: Pedidos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("totalCompra, id, empleadoId, clienteId, nroTraking,comentarios,fechaEnvio,fechaInicio,estado")] Pedido pedido)
        {
            if (id != pedido.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pedido);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PedidoExists(pedido.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pedido);
        }

        // GET: Pedidos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos
                .FirstOrDefaultAsync(m => m.id == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // POST: Pedidos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pedido = await _context.Pedidos.FindAsync(id);
            _context.Pedidos.Remove(pedido);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PedidoExists(int id)
        {
            return _context.Pedidos.Any(e => e.id == id);
        }
    }
}

Seguimiento/Views/Carritos/Create.cshtml
@model Seguimiento.Models.Carrito

@{
    ViewData["Title"] = "Create";
}

<h4 class="titulos_creacion">Crear el carrito</h4>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="idProducto" class="control-label"></label>
                <input asp-for="idProducto" class="form-control" />
                <span asp-validation-for="idProducto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="CREAR" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver al listado</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Seguimiento/Views/Carritos/Delete.cshtml
@model Seguimiento.Models.Carrito

@{
    ViewData["Title"] = "Delete";
}


<h3 class="titulos_borrar">¿Seguro que quieres borrar el carrito?</h3>
<div>
    <h4>Carrito</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.idProducto)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.idProducto)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="BORRAR" class="btn btn-danger" /> |
        <a asp-action="Index">Volver al listado</a>
    </form>
</div>

Seguimiento/Views/Carritos/Details.cshtml
@model Seguimiento.Models.Carrito

@{
    ViewData["Title"] = "Details";
}

<h4 class="titulos_detalles">Detalles del carrito</h4>

<div>
    <h4>Carrito</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.idProducto)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.idProducto)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Editar</a> |
    <a asp-action="Index">Volver al listado</a>
</div>

Seguimiento/Views/Carritos/Edit.cshtml
@model Seguimiento.Models.Carrito

@{
    ViewData["Title"] = "Edit";
}

<h4 class="titulos_editar">Editar el carrito</h4>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="idProducto" class="control-label"></label>
                <input asp-for="idProducto" class="form-control" />
                <span asp-validation-for="idProducto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="GUARDAR" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver al listado</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Seguimiento/Views/Carritos/Index.cshtml
@model IEnumerable<Seguimiento.Models.Carrito>

@{
    ViewData["Title"] = "Index";
}

<div class="imagen_superior">
    <h1 class="titulo">Carrito</h1>
    <div class="d-flex p-0 bd-highlight">
            <button class="btn btn-link" data-toggle="modal" data-target="#procesar" style="color: forestgreen; padding: 0px; margin-bottom: 1rem">
                Procesar Envio
            </button>
            <p style="margin: 0px 10px 0px 10px;"> || </p>
            <button class="btn btn-link" data-toggle="modal" data-target="#myModal" style="color: orangered; padding: 0px; margin-bottom: 1rem">
                Eliminar Carrito
            </button>
    </div>
</div>
<div class="row">
    <div class="col-lg-4">
        <br />
        @using (Html.BeginForm("Crear", "Pedidos"))
        {
            <label><strong>TOTAL CARRITO</strong></label><br />
            <input type="hidden" name="totalCompra" value=@ViewBag.total />
            <h3>$@ViewBag.total</h3>
            <label><strong>FECHA DE HOY</strong></label><br />
            <input type="datetime-local" name="fechaInicio" required/><br /><hr />
            <label><strong>ENCARGADO DE ENVÍO</strong></label><br />
            <select name="empleadoId" style="width:13rem;" class="form-select form-control-md" required>
                <option selected >Login</option>
                @if (ViewBag.emp != null)
                {
                    foreach (var e in ViewBag.emp)
                    {
                        <option value="@e.legajo">@e.nombre @e.apellido</option>
                    }
                }
            </select>
            <hr />
            <label><strong>CLIENTE</strong></label><br />
            <select name="clienteId" style="width:13rem;" class="form-select form-control-md" required>
                <option selected>Cliente</option>
                @if (ViewBag.cli != null)
                {
                    foreach (var c in ViewBag.cli)
                    {
                        <option value="@c.id">@c.nombre @c.apellido</option>
                    }
                }
            </select><br />
            <hr />
            <label><strong>COMENTARIOS</strong></label><br />
            <textarea name="comentarios" style="height:110px; width:auto;"></textarea>
            @*MODAL*@
            <div id="procesar" class="modal fade" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <div class="modal-body">
                            <p>¿Confirma que desea procesar el carrito?</p>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-success">Procesar</button>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="col-sm-8">
        <table class="table">
            <thead>
                <tr>
                    <th class="celdas">
                        @Html.DisplayNameFor(model => model.idProducto).ToUpper()
                    </th>
                    <th class="celdas">
                        NOMBRE
                    </th>
                    <th class="celdas">
                        PRECIO
                    </th>
                    <th class="celdas">
                        TALLE
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.idProducto)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.idNombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.idPrecio)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.idTalle)
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>

        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <p>¿Esta seguro que desea eliminar el carrito?</p>
                    </div>
                    <div class="modal-footer">
                        @using (Html.BeginForm("DeleteAll", "Carritos"))
                        {
                            <button type="submit" class="btn btn-danger">Eliminar</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>